language: python
python:
 - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: py.test

# after tests, report test coverage to coveralls
after_success:
 - coveralls

notifications:
  email:
    recipients:
      - mathintersectprogramming@gmail.com
    on_success: never
    on_failure: change
