version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install cmake
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Test
          command: |
              python -m pytest --doctest-modules -v --cov-report term-missing --cov
              coveralls
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - build-and-test
